---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp: ["25.3", "26.1"]
        rebar3: ['3.22.1']
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: python3 python3-httpbin python3-pip
          version: 1.1
      - run: |
          pip3 install gunicorn
          gunicorn -b 127.0.0.1:8000 -b unix:httpbin.sock httpbin:app&
      - run: rebar3 xref
      - run: rebar3 eunit
      - run: rebar3 dialyzer
  legacy:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp: ["22.3", "23.3", "24.3"]
        rebar3: ['3.18.0']
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: python3 python3-httpbin python3-pip
          version: 1.1
      - run: |
          pip3 install gunicorn
          gunicorn -b 127.0.0.1:8000 -b unix:httpbin.sock httpbin:app&
      - run: rebar3 xref
      - run: rebar3 eunit
      - run: rebar3 dialyzer


